### PR TITLE
Fix urls in versions list used in the build context

### PR DESCRIPTION
**Pull request by pdavide**
- add publisher slug
- add publisher_project slug

### CODE REVIEW

**Review by xrmx — COMMENTED** [review]
How are these paths used? I think they should be added to project path so they should not start from root.

**Review by xrmx — COMMENTED** [review]
Unless these are supposed to work only on a subdomain setup. Anyway the commit message should tell why this fixes something :)

**Comment by pdavide** [comment]
These path are used to generate links to the different versions of a document.
When on readthedocs.org, the absolute path is correctly set to `/{{ version.project.language }}/{{ version.slug}}/` because the document URL scheme is `://project-slug.readthedocs.io/language/version`.
In Docs Italia the absolute path needs to be changed because the document URL scheme is `://docs.italia.it/publisher-slug/publisher_project-slug/project-slug/language/version`.

**Comment by pdavide** [comment]
@francescozaia can we merge here?

**Review by yakky — APPROVED** [review]

**Pull request merged**
